### PR TITLE
New*er* built-ins

### PR DESCRIPTION
**Pull request by vihanb**
In these commits I've added a few things that I think will help Japt.

---
## Autogolfing

Now, the `shorthand()` function when provided with a second argument, will auto-golf the code.
You can call this and it will return the auto-golfed code.

Call it without the second argument and the code will be un-auto-golfed

---
## [String compression](https://github.com/ETHproductions/Japt/pull/4/files#diff-d37029f134ae829dd65c2c2a4f786eadR133)

I've currently [commented](https://github.com/ETHproductions/Japt/pull/4/files#diff-d37029f134ae829dd65c2c2a4f786eadR137) this code out as you'll need to include the shoco library (more info in the code).

This adds two functions. [`shoco.c`](https://github.com/ETHproductions/Japt/pull/4/files#diff-d37029f134ae829dd65c2c2a4f786eadR138) for compression, and [`shoco.d`](https://github.com/ETHproductions/Japt/pull/4/files#diff-d37029f134ae829dd65c2c2a4f786eadR140) for decompression. 

TeaScript uses `L` to reference shoco but that's currently in use so I've left it up to you to decide where you'd like to go with that

---
## Function changes
I've made _slight_ changes to a few functions.

 - `String.prototype.m` accepts a second argument, this means `qS m@<code> qS` can become `m@<code>,S`.

 - `String.prototype.k` accepts flags as a second argument.

 - `Array.prototype.r` accepts a second reduce argument as reduce functions often use them.

---
## New functions

I've added a few new functions.

 - `String.prototype.e` are the recursive replaces

 - `Number.prototype.a` runs `Math.abs`

 - `Number.prototype.l` runs `Math.factorial`

 - `Math.g` is fibonacci

 - `Math.p` is prime factorization

 - `Array.prototype.u` runs `[].unshift(x)`

 - `Array.prototype.v` runs `[].shift()`

---
## New shortened property names
I've shortened a few property names:

 - `Math.t` => `Math.atan2`
 - `Math.f` => `Math.factorial`

---
## New unicode shortcuts
I've added a few new unicode shortcuts

 - `£` (0xA3 163) => `m@`
 - `¤` (0xA4 164) => `==`

---

Thanks, Vihan

### CODE REVIEW

**Comment by ETHproductions** [comment]
Whoops, sorry I didn't see this! Now that I've pushed a different commit, it's telling me there are conflicts to resolve. I'm not sure how to fix this (or even just undo the last commit)...

**Comment by ETHproductions** [comment]
Thanks again for the new functions and shortcuts! The new argument in `String.prototype.m` will surely save many bytes many times, as will the other edits. Now we need `!=`, `<=`, and `>=` shortcuts to go along with that `==` ;)

The addition to the autogolf function is really nice. I'll make it a prominent feature when I move the interpreter to my (very much WIP) GitHub-hosted site.

I'll try implementing shoco right now and see how it works. I moved the object to `O` for now, since that one wasn't being used at all.

---

Thanks again,
ETH

**Comment by ETHproductions** [comment]
Hmmm..... Testing with the code `Oc"this"`, I get this error message:

    abort() at za@http://ed-von-schleck.github.io/shoco/shoco.js:29:21
    z@http://ed-von-schleck.github.io/shoco/shoco.js:132:283
    v.Ja@http://ed-von-schleck.github.io/shoco/shoco.js:18:72
    xa@http://ed-von-schleck.github.io/shoco/shoco.js:52:23
    p.preRun/c.compress@http://ed-von-schleck.github.io/shoco/shoco.js:2:212
    shoco.c@https://raw.githubusercontent.com/ETHproductions/Japt/master/src/japt-interpreter.js:137:60
    @https://raw.githubusercontent.com/ETHproductions/Japt/master/src/japt-interpreter.js line 360 > eval:1:1
    evalJapt@https://raw.githubusercontent.com/ETHproductions/Japt/master/src/japt- interpreter.js:360:16
    run@https://raw.githubusercontent.com/ETHproductions/Japt/master/src/japt-interpreter.js:283:3
    onclick@http://stacksnippets.net/js:1:1

    If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.

Do you have any idea why this is? I'm certain you're more knowledgeable with this library than I am.

**Comment by vihanb** [comment]
Huh, I was taking a look at that too. It seems like it has something to do with cross-origin resource sharing but that doesn't seem to be the case. The script does do some AJAX request so I'll be investigating those

**Comment by vihanb** [comment]
Okay, well I fixed it \o/, I'll request to add the shoco library directly to the Japt github so Japt doesn't need to rely on me for hosting the shock library.

**Pull request merged**
