### PR TITLE
Shoco for Japt

### PR DESCRIPTION
**Pull request by vihanb**
Adds shoco.js to Japt's Github.

### CODE REVIEW

**Comment by ETHproductions** [comment]
Thanks! I'll test it out now, then I'm off to bed.

**Comment by ETHproductions** [comment]
Awesome, it works now, but it gives me a few unprintables for "this and that". Is this normal?

**Comment by vihanb** [comment]
That's normal, some strings might have unprintables. I could use a `prompt` if the unprintables don't output to the textbox. Hopefully they do

**Comment by ETHproductions** [comment]
Yep, they do. If I really needed to, I could use `Oc"..." a m@Xc` to get the char codes. Thanks again for all your work on this!

**Pull request merged**
