### PR TITLE
Array and Math built-ins & default arguments 

### PR DESCRIPTION
**Pull request by vihanb**
In the last few commits, I've added some new array and math built-ins.

---

I hope I'm not taking up all the `Array.prototype` property names so I've added two empty unicode property names.

They don't seem to have any encoding issues on GitHub so hopefully it'll work fine.

---
## Built-ins

 - `[].x` is a sum function. It returns the sum of all the elements in the array.
 - `[].y` is a transpose function. It transposes the array. An example:

    |1 2 3|
    |4 5 6|
    |7 8 9|

when transposed would become:

    |1 4 7|
    |2 5 8|
    |3 6 9|

This works with strings, they will automatically be split if needed.

 - `Math.h` is `Math.hypot`, it returns the sum of the squares of all the provided arguments.

---
## Defaults

Nothing much here

 - `"".q` (split) now the first argument defaults to `""`

 - `[].q` (join) now the first argument defaults to `""`

### CODE REVIEW

**Comment by ETHproductions** [comment]
Thanks for the new transpose built-in! Transposing arrays/strings is pretty much the hardest common code-golf task to get short in JS. Summation is another unnecessarily long common task.

---

This language is really going places, thanks to you :-) Now we need to merge all of the awesome new features into the 0.2 interpreter. Would this be easier if 0.2 was its own branch instead of just a separate file?

**Comment by ETHproductions** [comment]
Oh, now that I think about it, rotation would be another good feature to go along with the transposition.

**Comment by vihanb** [comment]
I'd say v0.2 should be in a separate branch so changes can be merged easily. I'd also suggest instead of v0.2, to just go to v2.

I haven't decided how rotation might work but I might borrow some 2D transformation from another [language](http://vihanserver.tk/p/langs/Unnamed/main.js) I wrote which might help with array rotations and ascii-art.

**Comment by ETHproductions** [comment]
Thanks again for the input. Yeah, I guess just dropping the 0s from the release names is a good idea.

I think it would be simplest to have one function to handle rotation, with an input of 1, 2, or 3 for rotations of 90, 180, and 270 degrees, respectively. This shouldn't be too hard to implement. Also, I noticed the problem with the transpose function, but I'm not sure why this happens. Do you have any idea?

**Comment by vihanb** [comment]
Yeah, I already committed the change with the transpose fix. I'll request to merge it.

**Pull request merged**
